name: general_env
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - numpy
  - tqdm
  - numba
  - pandas
  - scikit-learn
  - matplotlib
  - ipython
  - ipykernel
  - pip:
    - ucimlrepo
